[package]
name = "caret_trace"
version.workspace = true
edition.workspace = true
description = "Tracing and observability for Caret"
license.workspace = true
repository.workspace = true
authors.workspace = true

[dependencies]
caret_core.workspace = true
caret_metrics.workspace = true
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
tracing-core = "0.1"
parking_lot = "0.12"
serde_json = "1.0"
